### PR TITLE
Add xact locks support

### PR DESCRIPTION
**Pull request by alexey-sveshnikov**
Hi!

Here is a pg_advisory_xact_lock (and friends) support.

### CODE REVIEW

**Comment by MythicManiac** [comment]
This is a change that would be useful for us too, given that we use PgBouncer in transaction pooling mode

**Comment by Xof** [comment]
This isn't a safe feature.

For example:

```with atomic():
         with advisory_lock(xact=True):
            do_things()
         do_more_things()```

The clear expectation is that `do_more_things()` will be outside the advisory lock, but it's not, because there's no way to release a transaction-scoped advisory lock except to end the transaction. Transaction-scoped advisory locks were actually implemented in an earlier version, and were removed for this reason.

**Comment by MythicManiac** [comment]
Wouldn't that be more of an issue with documentation / shoving everything behinde the same function interface? Maybe you could have a context manager around _transactions_ themselves?

**Comment by Xof** [comment]
Well, there is a context manager than handles transactions already; it's `atomic()`. But the entire point of the `advisory_lock` decorator is that you know that the lock as been taken, and that it is released when you exit. The semantics of a context manager really demand that any resources it takes are released at the end. I don't think you can document your way out of that.

It might make sense to have a helper function as part of the module that takes a transaction-scoped advisory lock that you could use in concert with `atomic()`, such as:

    with atomic():
        pg_locks.xact_advisory_lock('my lock')

... with no matching release function.

**Comment by MythicManiac** [comment]
As I understand it, all we have to ensure is that:
1. An xact advisory lock is called only during a transaction
2. An xact advisory lock cannot be assumed released before the transaction(s) is closed

So would something akin this work?
```python
@contextmanager
def atomic_lock(lock_id, shared=False, wait=True, using=None, savepoint=True):
    from django.db import DEFAULT_DB_ALIAS, connections, transaction

    if using is None:
        using = DEFAULT_DB_ALIAS

    if connections[using].in_atomic_block:
        raise ValueError("Unable to acquire a transaction scoped lock while already in a transaction")
    
    with transaction.atomic(using=using, savepoint=savepoint):
        yield get_xact_lock(lock_id, shared, wait)
```

Basically just wrap Django's `transaction.atomic` entirely and prevent it being called unless we have full control of the transaction state.

**Comment by MythicManiac** [comment]
Here's how we solved the issue in case it's useful for anyone:

https://github.com/thunderstore-io/Thunderstore/blob/master/django/thunderstore/core/transactions.py

**Pull request closed without merging**
