### PR TITLE
Add possibility to check if advisory lock was acquired already

### PR DESCRIPTION
**Pull request by alexole**
Add function advisory_lock_acquired to check if lock was acquired.

### CODE REVIEW

**Comment by Xof** [comment]
Can you describe the use case here? Given that the result of the lock acquisition is available inside the context, I'm not use I understand the need for a separate function to test it.

**Comment by alexole** [comment]
I see it might be very specific, but for me the use case is: I have a Django management command which forks and runs exclusively a long-running job in a separate process. And to make it exclusive context manager works fine here. The problem is: this management command can be also called via API and in case if lock already acquired I have to report error to the API client.

**Comment by Chronial** [comment]
Note that there is a race condition in how you want to do that: Somebody else could get the lock between the time when you check this and later on actually get the lock.

That is also the reason why a function like this is a bad idea: It only invites people to write broken code. I would advise against putting something like this into this library.

**Comment by alexole** [comment]
@Chronial yes, there is race condition, but this check is more informational for me, for long running process I want to check the status, I don't want to try locking, task will be anyway executed exclusively, because it's inside the context manager block.

**Comment by Chronial** [comment]
Don't these two snippets have identical results?

```
lock_held = advisory_lock_acquired('mylock')
```

```
with advisory_lock('mylock', wait=False) as lock_held:
    pass
```

**Comment by alexole** [comment]
@Chronial no, the first one does not lock, the second does.

**Comment by Chronial** [comment]
I understand that, but isn't the outcome exactly the same in 100% of situations?

**Comment by alexole** [comment]
If you want to get the state of lock for e.g. UI purposes or so and do not want to interfere with another lock - it would make sense.

**Pull request closed without merging**
